#!/bin/bash
# Post-generation script to add manual controller setup

SETUP_FILE="internal/controller/zz_setup.go"

echo "Adding manual controller setup to zz_setup.go..."

# Check if the manual setup call already exists
if grep -q "SetupManual" "$SETUP_FILE"; then
    echo "Manual setup already exists in zz_setup.go"
    exit 0
fi

# Add the manual setup call before the final return
sed -i.bak '/return nil$/i\
\
	// MANUAL CONTROLLER SETUP - DO NOT REMOVE\
	// Setup manual controllers that are not generated by upjet\
	if err := SetupManual(mgr, o); err != nil {\
		return err\
	}\
	// END MANUAL CONTROLLER SETUP\
' "$SETUP_FILE"

# Remove backup file
rm -f "$SETUP_FILE.bak"

echo "Manual controller setup added to zz_setup.go"
